### ISSUE TITLE
“Precision must be a non-negative integer”

### ISSUE THREAD

**Issue by tomek-he-him** [bendrucker/round.js#3]
Hi!

Whenever I evaluate `round(…, 100)`, I get  the error `Uncaught Error: Precision must be a non-negative integer`.

Funnily enough, `round(…, 99)` and `round(…, 101)` seem to be ok.

**Comment by bendrucker** [comment]
Good catch! Fixed this upstream.

**Comment by tomek-he-him** [comment]
Thanks! Works like a charm!
